{% set name = "roocs-utils" %}
{% set package_name = "roocs_utils" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ package_name }}-{{ version }}.tar.gz
  sha256: 29ace2e0e741bb3ff9aaf8deb5240f82fca0fa0b93e7809a3f3479973778611a

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - numpy >=1.16
    - xarray >=0.15
    - dask >=2.6
    - cftime
    - oyaml
    - pyyaml
    - netCDF4 >=1.4
    - python-dateutil >=2.8.1
    - cf_xarray >=0.2.1

test:
  imports:
    - roocs_utils

about:
  home: https://github.com/roocs/roocs-utils/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A package containing common components for the roocs project
  doc_url: https://roocs-utils.readthedocs.io/
  dev_url: https://github.com/roocs/roocs-utils/

extra:
  recipe-maintainers:
    - ellesmith88
    - agstephens
    - cehbrecht
    - Zeitsperre
