{% set name = "roocs-utils" %}
{% set package_name = "roocs_utils" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ package_name }}-{{ version }}.tar.gz
  sha256: 1cbedc1e5fcac227327f2bfedf0e93040aeba184ae9c7e2c8684c0d1f2c18324

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - aiohttp
    - cf_xarray >=0.3.1
    - cftime
    - dask >=2.6
    - fsspec
    - netCDF4 >=1.4
    - numpy >=1.16
    - python-dateutil >=2.8.1
    - xarray >=0.15
    - zarr
    - zstandard

test:
  imports:
    - roocs_utils
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/roocs/roocs-utils/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  license_url: https://github.com/roocs/roocs-utils/blob/master/LICENSE
  summary: A package containing common components for the roocs project
  dev_url: https://github.com/roocs/roocs-utils/
  doc_url: https://roocs-utils.readthedocs.io/
  doc_source_url: https://github.com/roocs/roocs-utils/blob/master/README.rst

extra:
  recipe-maintainers:
    - ellesmith88
    - agstephens
    - cehbrecht
    - Zeitsperre
