{% set name = "roocs-utils" %}
{% set package_name = "roocs_utils" %}
{% set version = "0.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ package_name }}-{{ version }}.tar.gz
  sha256: 5d34eeeef0b6ede1ca5545042acdb16f5897ad4062975a719ebd83317007503a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python >=3.8
    - aiohttp
    - cf_xarray >=0.3.1
    - cftime
    - dask >=2.6
    - fsspec
    - netCDF4 >=1.4
    - numpy >=1.16
    - python-dateutil >=2.8.1
    - xarray >=0.15
    - zarr
    - zstandard

test:
  imports:
    - roocs_utils
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/roocs/roocs-utils/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A package containing common components for the roocs project
  doc_url: https://roocs-utils.readthedocs.io/
  dev_url: https://github.com/roocs/roocs-utils/

extra:
  recipe-maintainers:
    - ellesmith88
    - agstephens
    - cehbrecht
    - Zeitsperre
